version: '3'

services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: flash-sale-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: flash_sale
      MYSQL_USER: flash_sale
      MYSQL_PASSWORD: flash_sale
    ports:
      - "3306:3306"
    volumes:
      - ./flash-sale-common/src/main/resources/db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - flash-sale-network

  # Redis
  redis:
    image: redis:6.2
    container_name: flash-sale-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - flash-sale-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: flash-sale-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - flash-sale-network

  # Nacos
  nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: flash-sale-nacos
    restart: always
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      NACOS_AUTH_ENABLE: "true"
      NACOS_AUTH_TOKEN_EXPIRE_SECONDS: 18000
      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
      JVM_XMS: 512m
      JVM_XMX: 512m
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
    networks:
      - flash-sale-network

volumes:
  mysql-data:
  redis-data:
  rabbitmq-data:

networks:
  flash-sale-network:
    driver: bridge 