server:
  port: 8005

spring:
  application:
    name: flash-sale-payment
  profiles:
    active: dev
  config:
    import: "optional:nacos:flash-sale-payment-dev.yml"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flash_sale?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 60000
      max-lifetime: 1800000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        name: ${spring.application.name}-${spring.profiles.active}

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.flashsale.payment.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always 