server:
  port: 8000

spring:
  application:
    name: flash-sale-user
  profiles:
    active: dev
  config:
    import: "optional:nacos:flash-sale-user-dev.yml"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flash_sale?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      connection-timeout: 5000
      validation-timeout: 3000
      initialization-fail-timeout: 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: 1000ms
          max-idle: 8
          min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: flash-sale
      config:
        server-addr: 127.0.0.1:8848
        group: flash-sale
        file-extension: yml
        name: ${spring.application.name}-${spring.profiles.active}

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.flashsale.user.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.flashsale.user: debug 