server:
  port: 8002

spring:
  application:
    name: flash-sale-product
  profiles:
    active: dev
  config:
    import: "optional:nacos:flash-sale-product-dev.yml"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flash_sale?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 60000
      max-lifetime: 1800000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  rabbitmq:
    enabled: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: flash-sale
      config:
        server-addr: 127.0.0.1:8848
        group: flash-sale
        file-extension: yml
        name: ${spring.application.name}-${spring.profiles.active}

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.flashsale.product.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.flashsale.product.mapper: debug 