server:
  port: 8080

spring:
  application:
    name: flash-sale-gateway
  profiles:
    active: dev
  config:
    import: "optional:nacos:flash-sale-gateway-dev.yml"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务发现地址
        group: flash-sale # 服务分组
      config:
        server-addr: 127.0.0.1:8848 # Nacos配置中心地址
        group: flash-sale # 配置分组
        file-extension: yml
        name: ${spring.application.name}-${spring.profiles.active}
  # 进行环境隔离，读取配置文件（可选）

    gateway:
      discovery:
        locator:
          enabled: true  # 启用服务发现定位器
          lower-case-service-id: true # 服务ID使用小写
      routes:
        # 用户服务路由
        - id: flash-sale-user
          uri: lb://flash-sale-user
          predicates: # 路径匹配规则
            - Path=/api/user/**
          filters:
            - StripPrefix=1  # 去除第一个路径前缀(api)，统一接口，减少微服务之间的路径重复(/api)
        
        # 产品服务路由
        - id: flash-sale-product
          uri: lb://flash-sale-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
        
        # 秒杀服务路由
        - id: flash-sale-seckill
          uri: lb://flash-sale-seckill
          predicates:
            - Path=/api/seckill/**
          filters:
            - StripPrefix=1
        
        # 订单服务路由
        - id: flash-sale-order
          uri: lb://flash-sale-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        
        # 支付服务路由
        - id: flash-sale-payment
          uri: lb://flash-sale-payment
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=1

# 日志配置
logging:
  level:
    com.flashsale.gateway: debug
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true #网关专属端点
# actuator配置，为后续全链路监控进行准备


