server:
  port: 8080

spring:
  application:
    name: flash-sale-gateway
  profiles:
    active: dev
  config:
    import: "optional:nacos:flash-sale-gateway-dev.yml"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: flash-sale
      config:
        server-addr: 127.0.0.1:8848
        group: flash-sale
        file-extension: yml
        name: ${spring.application.name}-${spring.profiles.active}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 用户服务路由
        - id: flash-sale-user
          uri: lb://flash-sale-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        
        # 产品服务路由
        - id: flash-sale-product
          uri: lb://flash-sale-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
        
        # 秒杀服务路由
        - id: flash-sale-seckill
          uri: lb://flash-sale-seckill
          predicates:
            - Path=/api/seckill/**
          filters:
            - StripPrefix=1
        
        # 订单服务路由
        - id: flash-sale-order
          uri: lb://flash-sale-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        
        # 支付服务路由
        - id: flash-sale-payment
          uri: lb://flash-sale-payment
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=1

# 日志配置
logging:
  level:
    com.flashsale.gateway: debug
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true



