server:
  port: 8080

spring:
  application:
    name: flash-sale-gateway
  profiles:
    active: dev
  config:
    import: "optional:nacos:flash-sale-gateway-dev.yml"
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: flash-sale
      config:
        server-addr: 127.0.0.1:8848
        group: flash-sale
        file-extension: yml
    gateway:
      # 默认过滤器
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      
      # 发现定位器配置
      discovery:
        locator:
          enabled: false # 关闭自动路由，使用手动配置
          lower-case-service-id: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"



