server:
  port: 8080

spring:
  application:
    name: flash-sale-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: flash-sale
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 秒杀服务路由
        - id: flash-sale-seckill
          uri: lb://flash-sale-seckill
          predicates:
            - Path=/api/seckill/**
          filters:
            - StripPrefix=1

logging:
  level:
    com.flashsale.gateway: debug 